source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
install! 'cocoapods', :share_schemes_for_development_pods => true
project '../../../FrameworksApp/FrameworksApp.xcodeproj'

pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'FrameworksApp' do
  supports_swift_versions '5.1'
  use_frameworks!
  pod 'ZappAppleVideoSubscriberSSO', :path => 'Files/ZappAppleVideoSubscriberSSO.podspec', :testspecs => ['UnitTests']
  pod 'ZappCore'
  pod 'React', :path => './node_modules/react-native', :subspecs => ['CxxBridge','DevSupport','RCTActionSheet','RCTNetwork','RCTWebSocket','RCTText','RCTImage','Core','RCTLinkingIOS','RCTAnimation']
  pod 'yoga', :path => './node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => './node_modules/react-native/third-party-podspecs/Folly.podspec'

  target 'FrameworksAppTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
  end
end
