module: ZappApple
module_version: 0.1.1

author: "Applicaster ltd."
copyright: "© 2019 [Applicaster ltd.](http://bustoutsolutions.com) under [Appache 2.0](https://github.com/applicaster/AppleApplicasterFrameworks/blob/master/LICENSE)."

author_url: https://www.applicaster.com
github_url: https://github.com/applicaster/AppleApplicasterFrameworks/tree/master/Frameworks/ZappCore

output: "../../../docs/ZappApple"
clean: true
min_acl: "public"
sdk: [iphone, appletv]
theme: jony
custom_categories:
  - name: Zapp App Root View Controller
    children:
      - SplashViewController
      - RootViewController
      - AppDelegateProtocol

  - name: Plugins
    children:
      - PluginsManager
      - AnalyticsManager
      - CrashlogsPluginsManager
      - PlayerDependantPluginsManager

  - name: AppLoading
    children:
      - DataManager
      - IdentityClient
      - IdentityClientBase
      - LoadingManager

  - name: CacheHelper
    children:
      - APCachedModel
      - APCacheHelper
      - APCacheManager
      - APFile
      - APFileLoadingCompletion
      - JsonSerializableProtocol

  - name: FeaturesCustomization
    children:
      - FeaturesCusimizationConsts
      - FeaturesCustomization

  - name: FeaturesCustomization
    children:
      - FeaturesCusimizationConsts
      - FeaturesCustomization

  - name: Keychain
    children:
      - HTTPStatusCode

  - name: Keys
    children:
      - AnalyticsKeys
      - AssetsKeys

  - name: Reachability
    children:
      - ReachabilityManager
      - ReachabilityManagerDelegate

  - name: StateMachine
    children:
      - LoadingStateMachineDataSource
      - LoadingStateMachineDelegate
      - LoadingState
      - LoadingStateConst
      - LoadingStateMachine

  - name: Storages
    children:
      - StoragesConsts
      - ZappStorageProtocol
      - LocalStorage
      - SessionStorage
      - StorageHelper
      - StorageInitialization

  - name: Styles
    children:
      - CoreStylesKeys
      - StylesHelper

  - name: UniversalSearch
    children:
      - SpotlightSubscription

  - name: UserInterfaceLayerManager
    children:
      - UserInterfaceLayerManager

  - name: Categories
    children:
      - AVURLAsset
      - String
      - UIApplication
      - UIColor
      - UIView
      - UIViewController
