# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ZappApple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ZappCore', :path => '../../../ZappCore.podspec'
  pod 'ReachabilitySwift', '= 4.3.0'
  pod 'AppCenter/Distribute', '= 2.3.0'

  target 'ZappAppleTests' do
    # Pods for testing
  end

end
