# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ZappCrashlogsMsAppCenter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ZappCore', :path => '../../../../../ZappCore.podspec'
  pod 'AppCenter/Crashes', '~> 2.5.3'

  # Pods for ZappCrashlogsMsAppCenter

  target 'ZappCrashlogsMsAppCenterTests' do
    # Pods for testing
  end

end
