source 'https://cdn.cocoapods.org/'
source 'git@github.com:applicaster/CocoaPods.git'

platform :ios, '11.0'
install! 'cocoapods', :share_schemes_for_development_pods => true
project '../../../../FrameworksApp/FrameworksApp.xcodeproj'

pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'FrameworksApp' do
  use_frameworks!
  pod 'ZappLocalNotifications', :path => './ZappLocalNotifications.podspec', :testspecs => ['UnitTests']
  pod 'ZappCore'

  target 'FrameworksAppTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
          config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
  end
end
